config/routes.rb
Demo::Application.routes.draw do
  
  root :to => 'posts#index'

  get "model/index"

  devise_for :models

  devise_for :users
  resources :tags
  resources :users 
  resources :posts do
    resources :comments
  end
  

  match ':controller(/:action(/:id))(.:format)'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    user ||= User.new # guest user (not logged in)
    if user.login
      can :manage, :all
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  attr_accessible :body, :user_id
  validates :body,  :presence => true
  
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title

  
  validates :title, :presence => true,
                    :length => { :minimum => 2 }

  has_many :comments
  has_and_belongs_to_many :tags
  belongs_to :user

  #CONFUSED !!!!!!!!!!!
  # definition of method tag! 
  # which has been used in posts_controller's create definition
  def tag!(tags)
		tags = tags.split(" ").map do |tag|
			Tag.find_or_create_by_name(tag)
		end
		self.tags << tags
	end

end

app/models/role.rb
class Role < ActiveRecord::Base
	has_and_belongs_to_many :users, :join_table => :users_roles
	belongs_to :resource, :polymorphic => true

	scopify
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name

  has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
 
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :tags
  private

  def tags
    @tags = Tag.all
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(params[:comment])
    @comment.user_id = current_user.id

  	if @comment.save
  		redirect_to post_path(@post)   	
  	else
   	
    end
  end


end

app/controllers/model_controller.rb
class ModelController < ApplicationController
	before_filter :authenticate_model!
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]

  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 5, :order => 'updated_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @page_title = @post.title 

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = current_user.posts.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])

    unless current_user == @post.user 
      redirect_to @post, notice: " We're sorry, but something went wrong. "    
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.create(params[:post])
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        @post.tag!(params[:tags])

        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def application
    @tags = Tag.all

    render :layout => "application"
  end

	def index
    @tags = Tag.all
  end

	def show
		@tag = Tag.find(params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
	@user = User.find(params[:id])		
	end

	def index
		@user = User.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)
  	markdown_render = Redcarpet::Render::HTML.new(:hard_wrap => true, :no_styles => true)
  	markdown = Redcarpet::Markdown.new(markdown_render, :autolink => true, :no_intro_emphasis => true)
  	markdown.render(text.to_s)
	end

	def syntax_highlighter(html)
  	doc = Nokogiri::HTML(html)
  	doc.search("//pre[@lang]").each do |pre|
    	pre.replace Albino.colorize(pre.text.rstrip, pre[:lang])
  	end
  	doc.to_s
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/model_helper.rb
module ModelHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
  def tag_name(tags)
    tags.each do |tag|
      tag.name
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p>
  <b>Comment:</b>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               :confirm => 'Are you sure?',
               :method => :delete %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= @page_title || "Demo" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
 

    


    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="http://0.0.0.0:3000/">Demo</a>
          <div class="container nav-collapse">
            <ul class="nav">
            
            </ul>
            <ul class="nav pull-right">
              <% if user_signed_in? %>
                <li class="dropdown" id="user_menu">
                  <a href="#user_menu" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %> <b class='caret'></b></a>
                  <ul class="dropdown-menu">
                    <li class="first"><%= link_to "My archive", current_user %></li>
                    <li><%= link_to "New Posts", new_post_path %></li>
                    <li><%= link_to "Account settings", edit_user_registration_path %></li>
                    <li class="last"><%= link_to "Sign out", destroy_user_session_path %></li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Sign up", new_user_registration_path  %></li>
                <li><%= link_to "Sign in", new_user_session_path  %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>



    <div class="container">
        <br />
        <br />
        <br />
        <div class="row">
          <div class="span9">
            <% unless notice.blank? %>
              <p class="notice" ><%= notice %></p>
            <% end %>
            <% unless alert.blank? %>
              <p class="alert" ><%= alert %></p>
            <% end %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Tags</h3>
              <ul class="nav nav-list">
                <% @tags.each do |tag| %>
                <li><%= link_to tag.name, tag_path(tag) %> </li>
                <% end %>
                <li><%= link_to '瞎扯蛋', :controller => 'tags', :action => 'show', :id => '1' %></li>
                <li><%= link_to '扯蛋', :controller => 'tags', :action => 'show', :id => '2' %></li>
                <li><%= link_to '扯馄蛋', :controller => 'tags', :action => 'show', :id => '3' %></li>
                <li><%= link_to '混蛋', :controller => 'tags', :action => 'show', :id => '4' %></li>
                <li><%= link_to '混八蛋', :controller => 'tags', :action => 'show', :id => '5' %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer align="center">
        <br /> <br />
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/posts/_form.html.erb
<br />
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
    <%= f.label :tags %>
    <%= text_field_tag :tags, params[:tags] %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post_list.html.erb
<% posts.each do |post| %>
  <li>
    <h5 class="title"><%= link_to post.title, :controller => 'posts', :action => 'show', :id => post %></h5>
  </li>
<% end %>

app/views/posts/edit.html.erb
<br /><br />
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>
<br /> <br />

<% @posts.each do |post| %>
  <li>
    <h3 class="title"><%= link_to post.title, :controller => 'posts', :action => 'show', :id => post %></h3>
    
    <h5>Create by <%= link_to post.user.email,post.user %> at <%= time_tag(post.created_at) %> </h5>
    <%=raw markdown(truncate(post.content, :length => 80, :omission => '...')) %>
  
    <%= link_to '查看全文', :controller => 'posts', :action => 'show', :id => post %>>>
  </li>
  ...............................................................................................................................................................................
<% end %>

<%= will_paginate @posts %>

app/views/posts/new.html.erb
<br /><br />
<h4>New post</h4>
<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <h4>
    <br />
    <%= @post.title %>
  </h4>
</p>

<p>
  <%= raw markdown(@post.content) %>
</p>
<p>
  <% if current_user == @post.user %>
      
    [<%= link_to 'Edit', edit_post_path(@post) %>] 
  
    [<%= link_to 'Destroy', @post, :confirm => 'Are you sure?',
                                :method => :delete %>]
  <% end %>
</p>

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
<h5>Tag:</h5>
<% if @post.tags.exists? %>
  <%= @post.tags.each do |tag| %>
    <%= link_to tag.name, tag %>
  <% end %>
<% else %>
  There are no tags for this post.
<% end -%>
<br />
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
<h5>Comments:</h5>
<% @post.comments.each do |comment| %>

  <p>
    <%= comment.body %> ---- created by [<%= link_to comment.user.email, comment.user %>] <%= time_ago_in_words(comment.created_at)  %> ago.
  </p>
<% end %>

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  <h5>Add a comment:</h5>
  <%= form_for([@post, @post.comments.build]) do |f| %>

    <div class="field">
  
      <%= f.text_area :body %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>


<br />

app/views/tags/_form.html.erb
<% @tags.each do |tag| %>
	<li>
		<%= link_to tag.name, :controller => 'tags', :action => 'show', :id => tag %>
	</li>
<% end -%>

app/views/tags/index.html.erb
<%= render 'form' %>

app/views/tags/show.html.erb
<h2>Tag: <%= @tag.name %></h2>
-------------------------------------------------------------------------------------------------------------------------------------------------------
<h3>There are <%= @tag.posts.count %> posts in all. </h3>
<%= render 'posts/post_list', posts: @tag.posts %>

app/views/users/index.html.erb
<h3>All Users</h3>
<br /><br />
<% @user.each do |user| %>
	<li>
		<%= user.email %>
	</li>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.email %></h2>
----------------------------------------------------------------------------------------------------------------------------
<h3>There are <%= @user.posts.count %> posts in all. </h3>
<%= render 'posts/post_list', posts: @user.posts %>
----------------------------------------------------------------------------------------------------------------------------
<h3>And comments of others'posts.</h3>
<% @user.comments.each do |comment| %>
  <li>
    Commented <span>"<%= comment.body %>"</span> on <%= link_to comment.post.title, comment.post %> <%= time_ago_in_words(comment.created_at)  %> ago.
  </li>
<% end %>